# TCL File Generated by Component Editor 18.1
# Thu Oct 05 01:45:28 CEST 2023
# DO NOT MODIFY


# 
# mipi_controller "mipi_controller" v2.3
# Leonardo Tazzini 2023.10.05.01:45:28
# Mipi to Avalon Interface with builtin FIFO buffer
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module mipi_controller
# 
set_module_property DESCRIPTION "Mipi to Avalon Interface with builtin FIFO buffer"
set_module_property NAME mipi_controller
set_module_property VERSION 2.5
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Electrologic
set_module_property AUTHOR "Leonardo Tazzini"
set_module_property DISPLAY_NAME mipi_controller
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL mipi_controller
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file mipi_controller.vhd VHDL PATH mipi_controller.vhd TOP_LEVEL_FILE


# 
# documentation links
# 
add_documentation_link Website http://


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point avm
# 
add_interface avm avalon start
set_interface_property avm addressUnits WORDS
set_interface_property avm associatedClock clock
set_interface_property avm associatedReset reset
set_interface_property avm bitsPerSymbol 8
set_interface_property avm burstOnBurstBoundariesOnly false
set_interface_property avm burstcountUnits WORDS
set_interface_property avm doStreamReads false
set_interface_property avm doStreamWrites false
set_interface_property avm holdTime 0
set_interface_property avm linewrapBursts false
set_interface_property avm maximumPendingReadTransactions 0
set_interface_property avm maximumPendingWriteTransactions 0
set_interface_property avm readLatency 0
set_interface_property avm readWaitTime 1
set_interface_property avm setupTime 0
set_interface_property avm timingUnits Cycles
set_interface_property avm writeWaitTime 0
set_interface_property avm ENABLED true
set_interface_property avm EXPORT_OF ""
set_interface_property avm PORT_NAME_MAP ""
set_interface_property avm CMSIS_SVD_VARIABLES ""
set_interface_property avm SVD_ADDRESS_GROUP ""

add_interface_port avm avm_address address Output 32
add_interface_port avm avm_write write Output 1
add_interface_port avm avm_writedata writedata Output 16
add_interface_port avm avm_waitrequest waitrequest Input 1
add_interface_port avm avm_byteenable byteenable Output 2

# 
# connection point avs
# 
add_interface avs avalon end
set_interface_property avs addressUnits WORDS
set_interface_property avs associatedClock clock
set_interface_property avs associatedReset reset
set_interface_property avs bitsPerSymbol 8
set_interface_property avs burstOnBurstBoundariesOnly false
set_interface_property avs burstcountUnits WORDS
set_interface_property avs explicitAddressSpan 0
set_interface_property avs holdTime 0
set_interface_property avs linewrapBursts false
set_interface_property avs maximumPendingReadTransactions 0
set_interface_property avs maximumPendingWriteTransactions 0
set_interface_property avs readLatency 0
set_interface_property avs readWaitTime 1
set_interface_property avs setupTime 0
set_interface_property avs timingUnits Cycles
set_interface_property avs writeWaitTime 0
set_interface_property avs ENABLED true
set_interface_property avs EXPORT_OF ""
set_interface_property avs PORT_NAME_MAP ""
set_interface_property avs CMSIS_SVD_VARIABLES ""
set_interface_property avs SVD_ADDRESS_GROUP ""

add_interface_port avs avs_address address Input 8
add_interface_port avs avs_write write Input 1
add_interface_port avs avs_writedata writedata Input 32
add_interface_port avs avs_read read Input 1
add_interface_port avs avs_readdata readdata Output 32
set_interface_assignment avs embeddedsw.configuration.isFlash 0
set_interface_assignment avs embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avs embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avs embeddedsw.configuration.isPrintableDevice 0


# 
# connection point mipi
# 
add_interface mipi conduit end
set_interface_property mipi associatedClock ""
set_interface_property mipi associatedReset ""
set_interface_property mipi ENABLED true
set_interface_property mipi EXPORT_OF ""
set_interface_property mipi PORT_NAME_MAP ""
set_interface_property mipi CMSIS_SVD_VARIABLES ""
set_interface_property mipi SVD_ADDRESS_GROUP ""

add_interface_port mipi MIPI_PIXEL_CLK mipi_pixel_clk Input 1
add_interface_port mipi MIPI_PIXEL_D mipi_pixel_d Input 10
add_interface_port mipi MIPI_PIXEL_HS mipi_pixel_hs Input 1
add_interface_port mipi MIPI_PIXEL_VS mipi_pixel_vs Input 1

